name:                HaskellChess
version:             0.1.0.0
github:              "davideGiovannini/haskell_chess"
license:             BSD3
author:              "Davide Giovannini"
maintainer:          "giovannini.davide90@gmail.com"
copyright:           "2019 Davide Giovannini"



extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Simple Chess Game
category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/davideGiovannini/haskell_chess#readme>

dependencies:
  - base >= 4.8
  - gloss == 1.10.2.3
  - matrix == 0.3.5.0
  - vector == 0.11.0.0
  - JuicyPixels == 3.2.8

# library:
#   source-dirs: src

executables:
  haskell_chess-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -O2
    - -with-rtsopts=-N


# tests:
#   lol-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - lol
